name: payapp

description: Fintech APp

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.0+3

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #Local Hive Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  ansiparser: ^1.0.3

  #google SignIn
  google_sign_in: ^6.2.2

  #google maps
  google_maps_flutter: ^2.10.0


  #liquid swipe onBoardingScreen
  smooth_page_indicator: ^1.2.0+3

  #Google Fonts
  google_fonts: ^6.2.1

  #state Management
  provider: ^6.1.2

  #flutter svg
  flutter_svg: ^2.0.16

  #share& openUrl
  url_launcher: ^6.3.1

  #  localDatabase
  shared_preferences: ^2.3.3
  cached_network_image: ^3.4.1

  # otp autofill
  sms_autofill: ^2.4.1
  pin_input_text_field: ^4.5.2


  #imagePicker
  image_picker: ^1.1.2

  #permissionHandler
  permission_handler: ^11.3.1

  intl: ^0.19.0
  razorpay_flutter: ^1.3.7

  # lottie animation
  lottie: ^3.3.0
  visibility_detector: ^0.4.0+2
  flutter_riverpod: ^2.6.1
  miniplayer: ^1.0.0+2
  timeago: ^3.7.0
  http: ^1.2.2
  sizer: ^3.0.5
  socket_io_client: ^3.0.2
  readmore: ^3.0.0
  searchfield: ^1.2.1
  phonepe_payment_sdk: ^2.0.3
  crypto: ^3.0.6
  flutter_local_notifications: ^18.0.1
  get: ^4.6.6
  jiffy: ^6.3.2

  dropdown_button2: ^2.3.9
  syncfusion_flutter_sliders: ^28.1.33
  animated_text_kit: ^4.2.2
  rating_dialog: ^2.0.4
  ## from the E-commerce app:
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  ## disconnect
  url_strategy: ^0.3.0
  # pin_code_fields: ^8.0.1
  geolocator: ^13.0.2
  # google_maps_flutter_web: ^0.5.10
  flutter_typeahead: ^5.2.0
  carousel_slider: ^5.0.0
  shimmer_animation: ^2.2.1
  universal_html: ^2.2.4
  flutter_widget_from_html: ^0.15.3
  pointer_interceptor: ^0.10.1+2
  country_code_picker: ^3.1.0
  photo_view: ^0.15.0
  # outdated
  dotted_border: ^2.1.0
  share_plus: ^10.1.3
  # flutter_facebook_auth: ^7.1.1
  flutter_animarker: ^3.2.0
  # sign_in_with_apple: ^6.1.4
  just_the_tooltip: ^0.0.12
  flutter_slidable: ^3.1.2
  # outdated
  meta_seo: ^3.0.9
  # outdated
  animated_flip_counter: ^0.3.4
  speech_to_text: ^7.0.0
  flutter_box_transform: ^0.4.6
  dots_indicator: ^3.0.0
  location: ^7.0.1
  flutter_staggered_grid_view: ^0.7.0
  youtube_player_iframe: ^5.0.2
  time_range_picker: ^2.3.0
  fluttertoast: ^8.2.8
  dio: ^5.7.0
  image_cropper: ^8.0.2
  flutter_image_compress: ^2.3.0
  video_editor: ^3.0.0
  flutter_downloader: ^1.11.8
  glass: ^2.0.0+1
  glassmorphism: ^3.0.0
  youtube_parser: ^2.1.4
  cookie_jar: ^4.0.8
  rive: ^0.13.1
  easy_stepper: ^0.8.3
  flutter_animate: ^4.5.0
  auto_animated: ^3.1.0
  flutter_staggered_animations: ^1.1.1
  dotted_line: ^3.2.2
  font_awesome_flutter: ^10.7.0
  draggable_widget: ^2.0.0
  flutter_colorpicker: ^1.1.0
  pro_image_editor: ^6.1.3
  device_info_plus: ^11.2.0
  phone_numbers_parser: ^9.0.1
  uuid: ^4.5.1
  video_player: ^2.9.2
  flutter_inappwebview: ^6.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  http_parser: ^4.0.2
  chewie: ^1.8.5
  app_links: ^6.3.3
  geocoding: ^3.0.0
  youtube_player_flutter: ^9.1.1
  flutter_pdfview: ^1.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/image/
    - assets/language/
    - assets/education/
    - assets/onboarding/
    - assets/images/
    - assets/images/educationscreen/
    - assets/images/kycscreen/
    - assets/images/homescreen/
    - assets/images/homescreen/servicesicons/
    - assets/images/gmoappscreen/
    - assets/icons/
    - assets/data/
    - assets/payments/
    - assets/lottie/
    - assets/language/
    - assets/font/
    - assets/pod_service/
    - assets/RiveAssets/
    - assets/Backgrounds/
    - assets/WhatsApp Image 2024-03-19 at 21.56.13_a1be68bb.jpg
    - assets/map/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900

    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf
