// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuoT0sU1wTRFmaTPjD_I5FB271xfAzQTU',
    appId: '1:773473432182:android:116e28c2d74cdef428e557',
    messagingSenderId: '773473432182',
    projectId: 'sambhav-11d6e',
    storageBucket: 'sambhav-11d6e.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuzCquiHklic58otbNlqYAYvL2DRPwg_8',
    appId: '1:773473432182:web:d3bfa9b1792f369628e557',
    messagingSenderId: '773473432182',
    projectId: 'sambhav-11d6e',
    authDomain: 'sambhav-11d6e.firebaseapp.com',
    storageBucket: 'sambhav-11d6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZSnE_QmkIRZ5UeSrRwWALYn6N7e-bKLM',
    appId: '1:773473432182:ios:5922ff8db7a3f16c28e557',
    messagingSenderId: '773473432182',
    projectId: 'sambhav-11d6e',
    storageBucket: 'sambhav-11d6e.appspot.com',
    iosBundleId: 'com.sixamtech.6amMart',
  );

}